version: '3.9'
services:
  zookeeper:
    image: 'wurstmeister/zookeeper'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    networks:
      - fullstack

  kafka:
    image: 'wurstmeister/kafka'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_CREATE_TOPICS: 'quickstart-events:1:1,quickstart-events2:1:1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - fullstack

  mysql:
    image: mysql:latest
    container_name: bullshape-db
    restart: always
    environment:
      MYSQL_DATABASE: 'bullshape'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fullstack

 
  api:
    build: . 
    container_name: "bullshape-api"
    restart: always
    networks:
      - fullstack
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
  
volumes:
  mysql_data:

networks:
  fullstack:
    driver: bridge
