package models

const (
	GET_COMPANY_ERRCODE                 = 1100
	CREATE_COMPANY_EMPTY_PARAMS_ERRCODE = 1101
	CREATE_COMPANY_COMPANY_NAME_ERRCODE = 1102
)

const (
	CREATE_USER_WRONG_PARAMS_ERRCODE  = 2000
	CREATE_USER_DB_WRITE_FAIL_ERRCODE = 2001
)
