package models

const (
	GET_COMPANY_ERRCODE                       = 1100
	CREATE_COMPANY_EMPTY_PARAMS_ERRCODE       = 1101
	CREATE_COMPANY_COMPANY_NAME_ERRCODE       = 1102
	CREATE_COMPANY_COMPANY_WRONG_TYPE_ERRCODE = 1103
	DELETE_COMPANY_NO_ENTRY_ERRCODE           = 1104
	DELETE_COMPANY_COULD_NOT_DELETE_ERRCODE   = 1105
	UPDATE_COMPANY_NO_ENTRY_ERRCODE           = 1106
	UPDATE_COMPANY_COULD_NOT_UPDATE           = 1107
)

const (
	CREATE_USER_WRONG_PARAMS_ERRCODE  = 2000
	CREATE_USER_DB_WRITE_FAIL_ERRCODE = 2001
)
